DJANGO_SETTINGS_MODULE=settings.setting
# python manage.py createsuperuser --noinput
DJANGO_SUPERUSER_USERNAME=Unknowss
DJANGO_SUPERUSER_PASSWORD=Unknowss01
DJANGO_SUPERUSER_EMAIL=sirisak.unknowss@gmail.com
# DB settings
DJANGO_DB_ENGINE=django.db.backends.postgresql_psycopg2
DJANGO_DB_NAME=loanLabEquipment
DJANGO_DB_USER=postgres
DJANGO_DB_PASSWORD=Unknowss01
DJANGO_DB_HOST=localhost
DJANGO_DB_PORT=5432