version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: equipmentlab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: 
      context: ./web
      dockerfile: ./docker/prodRDS/Dockerfile
    volumes:
      - ./web:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./web/docker/prodRDS/.prodRDS
    command: "python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db  # ให้ Django รอ PostgreSQL รันก่อน

volumes:
  postgres_data:
