version: "3.9"
# Dev only
services:

  webApp:
    build: 
      context: ./webApp
      dockerfile: ./docker/prodRDS/Dockerfile
    volumes:
      - ./webApp:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./webApp/docker/prodRDS/.prodRDS
    command: "python manage.py runserver 0.0.0.0:8000"
    restart: always