version: "3.9"
# Dev only
services:

  web:
    build: 
      context: ./web
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./web:/usr/src/app/
    ports:
      - "8010:8000"
    env_file:
      - ./web/docker/.app
    command: "python manage.py runserver 0.0.0.0:8000"
    container_name: lab_web
    restart: always