version: "4.5"
# Dev only
services:

  web:
    image: postgres
    build: 
      context: ./webApp
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./webApp:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./webApp/docker/.app
    command: "python manage.py runserver 0.0.0.0:8000"
    networks:
      vpcbr:
        ipv4_address: 192.168.0.201

    restart: always

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.201/24
         gateway: 192.168.0.1