version: "3.9"
# Dev only
services:

  web:
    build: 
      context: ./web
      dockerfile: ./docker/prodRDS/Dockerfile
    volumes:
      - ./web:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./web/docker/prodRDS/.prodRDS
    command: "python manage.py runserver 0.0.0.0:8000"
    # command: gunicorn LabEquipmentLoanSystem.wsgi:application --preload --workers=3 --bind 0.0.0.0:8000 --forwarded-allow-ips="*"
    restart: always