from .base import *

"""
Django settings for LabEquipmentLoanSystem project.
Generated by 'django-admin startproject' using Django 3.2.7.
For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SECRET_KEY = 'Unknowss'
ALLOWED_HOSTS = ['*']